### ISSUE TITLE
mapa ari

### ISSUE THREAD

**Issue by 23620030** [SistemasTecTlaxiaco/actividad-4-mapa-mental-23620030#3]
[MAPA MATES ARIADNA 22.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-23620030/files/12679810/MAPA.MATES.ARIADNA.22.pdf)
![conjuntos](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-23620030/assets/143473537/48156735-72c1-4264-ba19-b34c59006962)

**Comment by DanAlejandr** [comment]
Manejo conceptual: 25% 
Relación entre los conjuntos: 25%
Calidad de la presentación: 25%
Jerarquía: 25%
Total 20/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..de bv...
